services:
- docker

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  - TF_VERSION=0.14.7

before_script:
  - docker build --target test --tag test .
  - docker build --tag $DOCKER_HUB_USERNAME/todo-app:latest --target production .

script:
  - docker run test tests
  - docker run test tests_integration
  - >
    docker run
    -e MONGO_DB_PRIMARY_CONNECTION_STRING
    test tests_e2e

install:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

after_script:
  - docker push $DOCKER_HUB_USERNAME/todo-app:latest

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: exercise-12