services:
- docker

before-install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

before_script:
  - docker build --target test --tag test .
  - docker build --tag $DOCKER_HUB_USERNAME/todo-app:latest --target production .

script:
  - docker run test tests
  - docker run test tests_integration
  - >
    docker run
    -e TRELLO_API_BASE_URL
    -e TRELLO_API_KEY
    -e TRELLO_API_TOKEN
    -e TRELLO_BOARD_ID
    test tests_e2e

after_script:
  - docker push $DOCKER_HUB_USERNAME/todo-app:latest

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: exercise-8