services:
- docker

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh  # install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com 

before_script:
  - docker build --target test --tag test .
  - docker build --tag $DOCKER_HUB_USERNAME/todo-app:latest --target production .
  - docker tag $DOCKER_HUB_USERNAME/todo-app:latest registry.heroku.com/$HEROKU_APP/web

script:
  - docker run test tests
  - docker run test tests_integration
  - >
    docker run
    -e TRELLO_API_BASE_URL
    -e TRELLO_API_KEY
    -e TRELLO_API_TOKEN
    -e TRELLO_BOARD_ID
    -e PORT
    test tests_e2e

after_script:
  - docker push $DOCKER_HUB_USERNAME/todo-app:latest

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: exercise-8