services:
- docker

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

before_script:
  - docker build --target test --tag test .
  - docker build --tag $DOCKER_HUB_USERNAME/todo-app:latest --target production .

script:
  - docker run test tests
  - docker run test tests_integration
  - >
    docker run
    -e MONGO_DB_PRIMARY_CONNECTION_STRING
    test tests_e2e

after_script:
  - docker push $DOCKER_HUB_USERNAME/todo-app:latest

deploy:
  provider: script
  script: 
      curl -dH -X POST "$AZURE_WEBHOOK"
  on:
    branch: exercise-11
