version: "3.4"

services:
  dev-app:
    build:
      context: .
      target: development
    image: todo-app:dev
    container_name: todo-app-dev
    env_file:
      - .env
    ports:
      - 8080:5000
    volumes:
      - ${PWD-.}:/src
  
  prod-app:
    build:
      context: .
      target: production
    image: todo-app:prod
    container_name: todo-app-prod
    env_file: 
     - .env
    ports:
      - "8080:8000"
  
  test:
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      TRELLO_API_BASE_URL: ${TRELLO_API_BASE_URL}
      TRELLO_API_KEY: ${TRELLO_KEY}
      TRELLO_API_TOKEN: ${TRELLO_TOKEN}
      TRELLO_BOARD_ID: ${TRELLO_BOARD_ID}
    build:
      context: .
      target: test