version: "3.8"

services:
  dev-app:
    build:
      context: .
      target: development
    image: todo-app:dev
    container_name: todo-app-dev
    env_file:
      - .env
    ports:
      - 8080:5000
    volumes:
      - ${PWD-.}:/src
  
  prod-app:
    build:
      context: .
      target: production
    image: todo-app:prod
    container_name: todo-app-prod
    env_file: 
     - .env
    ports:
      - "8080:8000"